name: first-github-action
on: [pull_request]
jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make py/packages
      - run: make py/codestyle
  